# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HOMA_PAGE_ARAYÜZ.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
import sys
import os

from Analizci import RGBMapAnalyzer 
from hava_durumu import WeatherFetcher


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(982, 813)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_HOME_PAGE_NAME = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(28)
        self.label_HOME_PAGE_NAME.setFont(font)
        self.label_HOME_PAGE_NAME.setObjectName("label_HOME_PAGE_NAME")
        self.verticalLayout_3.addWidget(self.label_HOME_PAGE_NAME)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget_farmermap = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_farmermap.setObjectName("tabWidget_farmermap")
        self.NEM_MAP = QtWidgets.QWidget()
        self.NEM_MAP.setObjectName("NEM_MAP")
        self.pushButton_Analiz_nem = QtWidgets.QPushButton(self.NEM_MAP)
        self.pushButton_Analiz_nem.setGeometry(QtCore.QRect(500, 320, 93, 28))
        self.pushButton_Analiz_nem.setObjectName("pushButton_Analiz_nem")
        self.tabWidget_farmermap.addTab(self.NEM_MAP, "")
        self.LIGHT_MAP = QtWidgets.QWidget()
        self.LIGHT_MAP.setObjectName("LIGHT_MAP")
        self.pushButton_analiz_isik = QtWidgets.QPushButton(self.LIGHT_MAP)
        self.pushButton_analiz_isik.setGeometry(QtCore.QRect(500, 320, 93, 28))
        self.pushButton_analiz_isik.setObjectName("pushButton_analiz_isik")
        self.tabWidget_farmermap.addTab(self.LIGHT_MAP, "")
        self.TEMPRATURE = QtWidgets.QWidget()
        self.TEMPRATURE.setObjectName("TEMPRATURE")
        self.tabWidget_farmermap.addTab(self.TEMPRATURE, "")
        self.horizontalLayout_2.addWidget(self.tabWidget_farmermap)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_analiz_sonucu = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")      # Daha modern ve okunur bir font
        font.setPointSize(16)           # Yazı boyutu
        font.setBold(True)              # Kalın yazı
        self.label_analiz_sonucu.setFont(font)
        
        self.label_analiz_sonucu.setAlignment(QtCore.Qt.AlignCenter)  # Ortala (isteğe bağlı)
        self.label_analiz_sonucu.setStyleSheet("""
            background-color: #e6f0ff;
            color: #002244;
            font-size: 16px;
            font-weight: bold;
            border: 2px solid #0055aa;
            border-radius: 8px;
            padding: 8px;
        """)


        self.label_analiz_sonucu.setObjectName("label_analiz_sonucu")
        self.verticalLayout_4.addWidget(self.label_analiz_sonucu)
        self.textBrowser_Analiz_sonucu = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_Analiz_sonucu.setObjectName("textBrowser_Analiz_sonucu")
        self.verticalLayout_4.addWidget(self.textBrowser_Analiz_sonucu)
        self.pushButton_analiz_scaklki = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_analiz_scaklki.setObjectName("pushButton_analiz_scaklki")
        self.verticalLayout_4.addWidget(self.pushButton_analiz_scaklki)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.widget_calendar = QtWidgets.QWidget(self.centralwidget)
        self.widget_calendar.setObjectName("widget_calendar")
        self.gridLayout.addWidget(self.widget_calendar, 2, 0, 2, 2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.calendar = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendar.setObjectName("calendar")
        self.horizontalLayout_3.addWidget(self.calendar)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_hatrlatma_notu = QtWidgets.QLabel(self.centralwidget)
        self.label_hatrlatma_notu.setObjectName("label_hatrlatma_notu")
        self.verticalLayout_2.addWidget(self.label_hatrlatma_notu)
        self.listWidget_hatrlatma_notlarm = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_hatrlatma_notlarm.setMinimumSize(QtCore.QSize(0, 100))
        self.listWidget_hatrlatma_notlarm.setObjectName("listWidget_hatrlatma_notlarm")
        self.verticalLayout_2.addWidget(self.listWidget_hatrlatma_notlarm)
        self.comboBox_Notlarm = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_Notlarm.setObjectName("comboBox_Notlarm")
        self.comboBox_Notlarm.addItem("")
        self.comboBox_Notlarm.addItem("")
        self.comboBox_Notlarm.addItem("")
        self.comboBox_Notlarm.addItem("")
        self.comboBox_Notlarm.addItem("")
        self.comboBox_Notlarm.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_Notlarm)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_CALENDAR_SIL = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_CALENDAR_SIL.setObjectName("pushButton_CALENDAR_SIL")
        self.horizontalLayout.addWidget(self.pushButton_CALENDAR_SIL)
        self.pushButton_CALENDAR_KAYDET = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_CALENDAR_KAYDET.setObjectName("pushButton_CALENDAR_KAYDET")
        self.horizontalLayout.addWidget(self.pushButton_CALENDAR_KAYDET)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_havadurumu = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)          # yazı boyutunu büyüt
        font.setBold(True)             # yazıyı kalın yap
        font.setFamily("Segoe UI")     # isteğe bağlı: modern font
        self.label_havadurumu.setFont(font)
        self.label_havadurumu.setAlignment(QtCore.Qt.AlignCenter)
        self.label_havadurumu.setStyleSheet("""
            color: #002244;
            font-size: 16px;
            font-weight: bold;
            border-top: 2px solid #0055aa;
            border-bottom: 2px solid #0055aa;
            padding-top: 6px;
            padding-bottom: 6px;
        """)

        self.label_havadurumu.setObjectName("label_havadurumu")
        self.verticalLayout.addWidget(self.label_havadurumu)
        self.textBrowser_Hava_durumu = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_Hava_durumu.setObjectName("textBrowser_Hava_durumu")
        self.verticalLayout.addWidget(self.textBrowser_Hava_durumu)
        self.pushButton_guncelle_havadurumu = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_guncelle_havadurumu.setObjectName("pushButton_guncelle_havadurumu")
        self.verticalLayout.addWidget(self.pushButton_guncelle_havadurumu)
        self.gridLayout.addLayout(self.verticalLayout, 3, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 982, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget_farmermap.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_HOME_PAGE_NAME.setText(_translate("MainWindow", "ZİRAİ ASİSTAN"))
        self.pushButton_Analiz_nem.setText(_translate("MainWindow", "ANALİZ ET"))
        self.tabWidget_farmermap.setTabText(self.tabWidget_farmermap.indexOf(self.NEM_MAP), _translate("MainWindow", "NEM HARİTASI"))
        self.pushButton_analiz_isik.setText(_translate("MainWindow", "ANALİZ ET"))
        self.tabWidget_farmermap.setTabText(self.tabWidget_farmermap.indexOf(self.LIGHT_MAP), _translate("MainWindow", "IŞIK MİKTARI HARİTASI"))
        self.tabWidget_farmermap.setTabText(self.tabWidget_farmermap.indexOf(self.TEMPRATURE), _translate("MainWindow", "SICAKLIK MİKTARI HARİTASI"))
        self.label_analiz_sonucu.setText(_translate("MainWindow", "Analiz Sonucu"))
        self.pushButton_analiz_scaklki.setText(_translate("MainWindow", "ANALİZ ET"))
        self.label_hatrlatma_notu.setText(_translate("MainWindow", "HATIRLATMA NOTLARIM"))
        self.comboBox_Notlarm.setItemText(0, _translate("MainWindow", "Gübreleme"))
        self.comboBox_Notlarm.setItemText(1, _translate("MainWindow", "Hasat"))
        self.comboBox_Notlarm.setItemText(2, _translate("MainWindow", "İlaçlama"))
        self.comboBox_Notlarm.setItemText(3, _translate("MainWindow", "Sulama"))
        self.comboBox_Notlarm.setItemText(4, _translate("MainWindow", "Ekim/Dikim"))
        self.comboBox_Notlarm.setItemText(5, _translate("MainWindow", "Çapalama"))
        self.pushButton_CALENDAR_SIL.setText(_translate("MainWindow", "SİL"))
        self.pushButton_CALENDAR_KAYDET.setText(_translate("MainWindow", "KAYDET"))
        self.label_havadurumu.setText(_translate("MainWindow", "HAVA DURUMU GÖSTERGESİ"))
        self.pushButton_guncelle_havadurumu.setText(_translate("MainWindow", "GÜNCELLE"))


