# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Manuel.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 318)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.Ileri_button = QtWidgets.QPushButton(Form)
        self.Ileri_button.setObjectName("Ileri_button")
        self.gridLayout.addWidget(self.Ileri_button, 0, 1, 1, 1)
        self.Sol_Button = QtWidgets.QPushButton(Form)
        self.Sol_Button.setObjectName("Sol_Button")
        self.gridLayout.addWidget(self.Sol_Button, 1, 0, 1, 1)
        self.Dur_button = QtWidgets.QPushButton(Form)
        self.Dur_button.setObjectName("Dur_button")
        self.gridLayout.addWidget(self.Dur_button, 1, 1, 1, 1)
        self.Sag_Button = QtWidgets.QPushButton(Form)
        self.Sag_Button.setObjectName("Sag_Button")
        self.gridLayout.addWidget(self.Sag_Button, 1, 2, 1, 1)
        self.Geri_Button = QtWidgets.QPushButton(Form)
        self.Geri_Button.setObjectName("Geri_Button")
        self.gridLayout.addWidget(self.Geri_Button, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.Change_Mode = QtWidgets.QPushButton(Form)
        self.Change_Mode.setObjectName("Change_Mode")
        self.verticalLayout.addWidget(self.Change_Mode)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        self.Change_Mode.clicked.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Ileri_button.setText(_translate("Form", "İleri"))
        self.Sol_Button.setText(_translate("Form", "Sol"))
        self.Dur_button.setText(_translate("Form", "Dur"))
        self.Sag_Button.setText(_translate("Form", "Sağ"))
        self.Geri_Button.setText(_translate("Form", "Geri"))
        self.Change_Mode.setText(_translate("Form", "Change Mode"))
