# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OOP2Final.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1021, 746)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.Main_Title = QtWidgets.QLabel(self.centralwidget)
        self.Main_Title.setMinimumSize(QtCore.QSize(489, 58))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.Main_Title.setFont(font)
        self.Main_Title.setObjectName("Main_Title")
        self.gridLayout.addWidget(self.Main_Title, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    font: bold 14px \"Segoe UI\";\n"
"    color: #34495e;\n"
"    border: 2px solid #3498db;\n"
"    border-radius: 10px;\n"
"    margin-top: 10px;\n"
"}\n"
"QLabel {\n"
"    font-size: 13px;\n"
"    color: #2c3e50;\n"
"}\n"
"QLineEdit {\n"
"    background-color: #ecf0f1;\n"
"    border: 1px solid #bdc3c7;\n"
"    border-radius: 5px;\n"
"    padding: 3px;\n"
"    font-size: 13px;\n"
"}\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Mod_label = QtWidgets.QLabel(self.groupBox)
        self.Mod_label.setStyleSheet("color: #2c3e50;            /* Yazı rengi */\n"
"font-weight: bold;         /* Kalın */\n"
"font-size: 14px;           /* Boyut */\n"
"font-family: \"Segoe UI\";   /* Yazı tipi */\n"
"")
        self.Mod_label.setObjectName("Mod_label")
        self.horizontalLayout_7.addWidget(self.Mod_label)
        self.Mod_Value = QtWidgets.QLabel(self.groupBox)
        self.Mod_Value.setObjectName("Mod_Value")
        self.horizontalLayout_7.addWidget(self.Mod_Value)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.system_label = QtWidgets.QLabel(self.groupBox)
        self.system_label.setStyleSheet("color: #2c3e50;            /* Yazı rengi */\n"
"font-weight: bold;         /* Kalın */\n"
"font-size: 14px;           /* Boyut */\n"
"font-family: \"Segoe UI\";   /* Yazı tipi */\n"
"")
        self.system_label.setObjectName("system_label")
        self.horizontalLayout_8.addWidget(self.system_label)
        self.system_value = QtWidgets.QLabel(self.groupBox)
        self.system_value.setObjectName("system_value")
        self.horizontalLayout_8.addWidget(self.system_value)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_8)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Battery_Label = QtWidgets.QLabel(self.groupBox)
        self.Battery_Label.setStyleSheet("color: #2c3e50;            /* Yazı rengi */\n"
"font-weight: bold;         /* Kalın */\n"
"font-size: 14px;           /* Boyut */\n"
"font-family: \"Segoe UI\";   /* Yazı tipi */\n"
"")
        self.Battery_Label.setObjectName("Battery_Label")
        self.horizontalLayout_2.addWidget(self.Battery_Label)
        self.Battery_Value = QtWidgets.QLabel(self.groupBox)
        self.Battery_Value.setObjectName("Battery_Value")
        self.horizontalLayout_2.addWidget(self.Battery_Value)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_2)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.haritalama_label = QtWidgets.QLabel(self.groupBox)
        self.haritalama_label.setStyleSheet("color: #2c3e50;            /* Yazı rengi */\n"
"font-weight: bold;         /* Kalın */\n"
"font-size: 14px;           /* Boyut */\n"
"font-family: \"Segoe UI\";   /* Yazı tipi */\n"
"")
        self.haritalama_label.setObjectName("haritalama_label")
        self.horizontalLayout_12.addWidget(self.haritalama_label)
        self.haritalama_value = QtWidgets.QLabel(self.groupBox)
        self.haritalama_value.setObjectName("haritalama_value")
        self.horizontalLayout_12.addWidget(self.haritalama_value)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_12)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Temp_Label = QtWidgets.QLabel(self.groupBox)
        self.Temp_Label.setStyleSheet("color: #2c3e50;            /* Yazı rengi */\n"
"font-weight: bold;         /* Kalın */\n"
"font-size: 14px;           /* Boyut */\n"
"font-family: \"Segoe UI\";   /* Yazı tipi */\n"
"")
        self.Temp_Label.setObjectName("Temp_Label")
        self.horizontalLayout_3.addWidget(self.Temp_Label)
        self.Temp_Value = QtWidgets.QLabel(self.groupBox)
        self.Temp_Value.setObjectName("Temp_Value")
        self.horizontalLayout_3.addWidget(self.Temp_Value)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_3)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.capalama_label = QtWidgets.QLabel(self.groupBox)
        self.capalama_label.setStyleSheet("color: #2c3e50;            /* Yazı rengi */\n"
"font-weight: bold;         /* Kalın */\n"
"font-size: 14px;           /* Boyut */\n"
"font-family: \"Segoe UI\";   /* Yazı tipi */\n"
"")
        self.capalama_label.setObjectName("capalama_label")
        self.horizontalLayout_13.addWidget(self.capalama_label)
        self.capalama_value = QtWidgets.QLabel(self.groupBox)
        self.capalama_value.setObjectName("capalama_value")
        self.horizontalLayout_13.addWidget(self.capalama_value)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_13)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Location_Label = QtWidgets.QLabel(self.groupBox)
        self.Location_Label.setStyleSheet("color: #2c3e50;            /* Yazı rengi */\n"
"font-weight: bold;         /* Kalın */\n"
"font-size: 14px;           /* Boyut */\n"
"font-family: \"Segoe UI\";   /* Yazı tipi */\n"
"")
        self.Location_Label.setObjectName("Location_Label")
        self.horizontalLayout_4.addWidget(self.Location_Label)
        self.Loc_X_Val = QtWidgets.QLabel(self.groupBox)
        self.Loc_X_Val.setObjectName("Loc_X_Val")
        self.horizontalLayout_4.addWidget(self.Loc_X_Val)
        self.Loc_Y_Val = QtWidgets.QLabel(self.groupBox)
        self.Loc_Y_Val.setObjectName("Loc_Y_Val")
        self.horizontalLayout_4.addWidget(self.Loc_Y_Val)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_4)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.loglama_label = QtWidgets.QLabel(self.groupBox)
        self.loglama_label.setStyleSheet("color: #2c3e50;            /* Yazı rengi */\n"
"font-weight: bold;         /* Kalın */\n"
"font-size: 14px;           /* Boyut */\n"
"font-family: \"Segoe UI\";   /* Yazı tipi */\n"
"")
        self.loglama_label.setObjectName("loglama_label")
        self.horizontalLayout_14.addWidget(self.loglama_label)
        self.loglama_value = QtWidgets.QLabel(self.groupBox)
        self.loglama_value.setObjectName("loglama_value")
        self.horizontalLayout_14.addWidget(self.loglama_value)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_14)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Speed_Label = QtWidgets.QLabel(self.groupBox)
        self.Speed_Label.setStyleSheet("color: #2c3e50;            /* Yazı rengi */\n"
"font-weight: bold;         /* Kalın */\n"
"font-size: 14px;           /* Boyut */\n"
"font-family: \"Segoe UI\";   /* Yazı tipi */\n"
"")
        self.Speed_Label.setObjectName("Speed_Label")
        self.horizontalLayout_5.addWidget(self.Speed_Label)
        self.Speed_Value = QtWidgets.QLabel(self.groupBox)
        self.Speed_Value.setObjectName("Speed_Value")
        self.horizontalLayout_5.addWidget(self.Speed_Value)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_5)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.Speed_Label_2 = QtWidgets.QLabel(self.groupBox)
        self.Speed_Label_2.setStyleSheet("color: #2c3e50;            /* Yazı rengi */\n"
"font-weight: bold;         /* Kalın */\n"
"font-size: 14px;           /* Boyut */\n"
"font-family: \"Segoe UI\";   /* Yazı tipi */\n"
"")
        self.Speed_Label_2.setObjectName("Speed_Label_2")
        self.horizontalLayout_16.addWidget(self.Speed_Label_2)
        self.Speed_Value_2 = QtWidgets.QLabel(self.groupBox)
        self.Speed_Value_2.setObjectName("Speed_Value_2")
        self.horizontalLayout_16.addWidget(self.Speed_Value_2)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_16)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.Speed_Label_4 = QtWidgets.QLabel(self.groupBox)
        self.Speed_Label_4.setStyleSheet("color: #2c3e50;            /* Yazı rengi */\n"
"font-weight: bold;         /* Kalın */\n"
"font-size: 14px;           /* Boyut */\n"
"font-family: \"Segoe UI\";   /* Yazı tipi */\n"
"")
        self.Speed_Label_4.setObjectName("Speed_Label_4")
        self.horizontalLayout_18.addWidget(self.Speed_Label_4)
        self.Speed_Value_4 = QtWidgets.QLabel(self.groupBox)
        self.Speed_Value_4.setObjectName("Speed_Value_4")
        self.horizontalLayout_18.addWidget(self.Speed_Value_4)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_18)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.Speed_Label_3 = QtWidgets.QLabel(self.groupBox)
        self.Speed_Label_3.setStyleSheet("color: #2c3e50;            /* Yazı rengi */\n"
"font-weight: bold;         /* Kalın */\n"
"font-size: 14px;           /* Boyut */\n"
"font-family: \"Segoe UI\";   /* Yazı tipi */\n"
"")
        self.Speed_Label_3.setObjectName("Speed_Label_3")
        self.horizontalLayout_17.addWidget(self.Speed_Label_3)
        self.Speed_Value_3 = QtWidgets.QLabel(self.groupBox)
        self.Speed_Value_3.setObjectName("Speed_Value_3")
        self.horizontalLayout_17.addWidget(self.Speed_Value_3)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_17)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setStyleSheet("color: #2c3e50;            /* Yazı rengi */\n"
"font-weight: bold;         /* Kalın */\n"
"font-size: 14px;           /* Boyut */\n"
"font-family: \"Segoe UI\";   /* Yazı tipi */\n"
"")
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.labelWarning1 = QtWidgets.QLabel(self.groupBox)
        self.labelWarning1.setText("")
        self.labelWarning1.setObjectName("labelWarning1")
        self.horizontalLayout_6.addWidget(self.labelWarning1)
        self.formLayout.setLayout(6, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_6)
        self.Detail_Check_Box = QtWidgets.QCheckBox(self.groupBox)
        self.Detail_Check_Box.setStyleSheet("color: #2c3e50;            /* Yazı rengi */\n"
"font-weight: bold;         /* Kalın */\n"
"font-size: 14px;           /* Boyut */\n"
"font-family: \"Segoe UI\";   /* Yazı tipi */\n"
"")
        self.Detail_Check_Box.setObjectName("Detail_Check_Box")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.Detail_Check_Box)
        self.gridLayout.addWidget(self.groupBox, 0, 1, 2, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setStyleSheet("QGroupBox {\n"
"    font: bold 14px \"Segoe UI\";\n"
"    color: #34495e;\n"
"    border: 2px solid #3498db;\n"
"    border-radius: 10px;\n"
"    margin-top: 10px;\n"
"}\n"
"QLabel {\n"
"    font-size: 13px;\n"
"    color: #2c3e50;\n"
"}\n"
"QLineEdit {\n"
"    background-color: #ecf0f1;\n"
"    border: 1px solid #bdc3c7;\n"
"    border-radius: 5px;\n"
"    padding: 3px;\n"
"    font-size: 13px;\n"
"}\n"
"")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ConnectButon = QtWidgets.QPushButton(self.groupBox_3)
        self.ConnectButon.setObjectName("ConnectButon")
        self.verticalLayout_3.addWidget(self.ConnectButon)
        self.DisconnectButton = QtWidgets.QPushButton(self.groupBox_3)
        self.DisconnectButton.setObjectName("DisconnectButton")
        self.verticalLayout_3.addWidget(self.DisconnectButton)
        self.horizontalLayout_15.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.StartMapping = QtWidgets.QPushButton(self.groupBox_3)
        self.StartMapping.setObjectName("StartMapping")
        self.verticalLayout_5.addWidget(self.StartMapping)
        self.StopMapping = QtWidgets.QPushButton(self.groupBox_3)
        self.StopMapping.setObjectName("StopMapping")
        self.verticalLayout_5.addWidget(self.StopMapping)
        self.horizontalLayout_15.addLayout(self.verticalLayout_5)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.CapalamaStart = QtWidgets.QPushButton(self.groupBox_3)
        self.CapalamaStart.setObjectName("CapalamaStart")
        self.verticalLayout_8.addWidget(self.CapalamaStart)
        self.CapalamaStop = QtWidgets.QPushButton(self.groupBox_3)
        self.CapalamaStop.setObjectName("CapalamaStop")
        self.verticalLayout_8.addWidget(self.CapalamaStop)
        self.horizontalLayout_15.addLayout(self.verticalLayout_8)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.log_start_buton = QtWidgets.QPushButton(self.groupBox_3)
        self.log_start_buton.setObjectName("log_start_buton")
        self.verticalLayout_10.addWidget(self.log_start_buton)
        self.log_stop_buton = QtWidgets.QPushButton(self.groupBox_3)
        self.log_stop_buton.setObjectName("log_stop_buton")
        self.verticalLayout_10.addWidget(self.log_stop_buton)
        self.horizontalLayout_15.addLayout(self.verticalLayout_10)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Speed_Bar = QtWidgets.QLabel(self.groupBox_3)
        self.Speed_Bar.setStyleSheet("color: #2c3e50;            /* Yazı rengi */\n"
"font-weight: bold;         /* Kalın */\n"
"font-size: 14px;           /* Boyut */\n"
"font-family: \"Segoe UI\";   /* Yazı tipi */\n"
"")
        self.Speed_Bar.setObjectName("Speed_Bar")
        self.horizontalLayout.addWidget(self.Speed_Bar)
        self.Speed_Value2 = QtWidgets.QLabel(self.groupBox_3)
        self.Speed_Value2.setObjectName("Speed_Value2")
        self.horizontalLayout.addWidget(self.Speed_Value2)
        self.Speed_horizontalSlideR = QtWidgets.QSlider(self.groupBox_3)
        self.Speed_horizontalSlideR.setOrientation(QtCore.Qt.Horizontal)
        self.Speed_horizontalSlideR.setObjectName("Speed_horizontalSlideR")
        self.horizontalLayout.addWidget(self.Speed_horizontalSlideR)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.Turn_Speed_Bar = QtWidgets.QLabel(self.groupBox_3)
        self.Turn_Speed_Bar.setStyleSheet("color: #2c3e50;            /* Yazı rengi */\n"
"font-weight: bold;         /* Kalın */\n"
"font-size: 14px;           /* Boyut */\n"
"font-family: \"Segoe UI\";   /* Yazı tipi */\n"
"")
        self.Turn_Speed_Bar.setObjectName("Turn_Speed_Bar")
        self.horizontalLayout_9.addWidget(self.Turn_Speed_Bar)
        self.Turn_Speed_value = QtWidgets.QLabel(self.groupBox_3)
        self.Turn_Speed_value.setObjectName("Turn_Speed_value")
        self.horizontalLayout_9.addWidget(self.Turn_Speed_value)
        self.Turn_Speed_Slider = QtWidgets.QSlider(self.groupBox_3)
        self.Turn_Speed_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Turn_Speed_Slider.setObjectName("Turn_Speed_Slider")
        self.horizontalLayout_9.addWidget(self.Turn_Speed_Slider)
        self.horizontalLayout.addLayout(self.horizontalLayout_9)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.Fren_Bar = QtWidgets.QLabel(self.groupBox_3)
        self.Fren_Bar.setStyleSheet("color: #2c3e50;            /* Yazı rengi */\n"
"font-weight: bold;         /* Kalın */\n"
"font-size: 14px;           /* Boyut */\n"
"font-family: \"Segoe UI\";   /* Yazı tipi */\n"
"")
        self.Fren_Bar.setObjectName("Fren_Bar")
        self.horizontalLayout_10.addWidget(self.Fren_Bar)
        self.Fren_Value = QtWidgets.QLabel(self.groupBox_3)
        self.Fren_Value.setObjectName("Fren_Value")
        self.horizontalLayout_10.addWidget(self.Fren_Value)
        self.Freen_Slider = QtWidgets.QSlider(self.groupBox_3)
        self.Freen_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Freen_Slider.setObjectName("Freen_Slider")
        self.horizontalLayout_10.addWidget(self.Freen_Slider)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.Capa_Bar = QtWidgets.QLabel(self.groupBox_3)
        self.Capa_Bar.setStyleSheet("color: #2c3e50;            /* Yazı rengi */\n"
"font-weight: bold;         /* Kalın */\n"
"font-size: 14px;           /* Boyut */\n"
"font-family: \"Segoe UI\";   /* Yazı tipi */\n"
"")
        self.Capa_Bar.setObjectName("Capa_Bar")
        self.horizontalLayout_11.addWidget(self.Capa_Bar)
        self.Capa_Value = QtWidgets.QLabel(self.groupBox_3)
        self.Capa_Value.setObjectName("Capa_Value")
        self.horizontalLayout_11.addWidget(self.Capa_Value)
        self.Capa_Slider = QtWidgets.QSlider(self.groupBox_3)
        self.Capa_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Capa_Slider.setObjectName("Capa_Slider")
        self.horizontalLayout_11.addWidget(self.Capa_Slider)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_11)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_15.addLayout(self.verticalLayout_6)
        self.gridLayout.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(711, 462))
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"    font: bold 14px \"Segoe UI\";\n"
"    color: #34495e;\n"
"    border: 2px solid #3498db;\n"
"    border-radius: 10px;\n"
"    margin-top: 10px;\n"
"}\n"
"QLabel {\n"
"    font-size: 13px;\n"
"    color: #2c3e50;\n"
"}\n"
"QLineEdit {\n"
"    background-color: #ecf0f1;\n"
"    border: 1px solid #bdc3c7;\n"
"    border-radius: 5px;\n"
"    padding: 3px;\n"
"    font-size: 13px;\n"
"}\n"
"")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Cam_View = QtWidgets.QFrame(self.groupBox_2)
        self.Cam_View.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Cam_View.setObjectName("Cam_View")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Cam_View)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.Cam_View)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(671, 412))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.Cam_View)
        self.gridLayout.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.Terminal_Group = QtWidgets.QGroupBox(self.centralwidget)
        self.Terminal_Group.setStyleSheet("QGroupBox {\n"
"    font: bold 14px \"Segoe UI\";\n"
"    color: #34495e;\n"
"    border: 2px solid #3498db;\n"
"    border-radius: 10px;\n"
"    margin-top: 10px;\n"
"}\n"
"QLabel {\n"
"    font-size: 13px;\n"
"    color: #2c3e50;\n"
"}\n"
"QLineEdit {\n"
"    background-color: #ecf0f1;\n"
"    border: 1px solid #bdc3c7;\n"
"    border-radius: 5px;\n"
"    padding: 3px;\n"
"    font-size: 13px;\n"
"}\n"
"")
        self.Terminal_Group.setObjectName("Terminal_Group")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Terminal_Group)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CmdReadOnly = QtWidgets.QTextEdit(self.Terminal_Group)
        self.CmdReadOnly.setObjectName("CmdReadOnly")
        self.verticalLayout.addWidget(self.CmdReadOnly)
        self.CmdEnter = QtWidgets.QLineEdit(self.Terminal_Group)
        self.CmdEnter.setObjectName("CmdEnter")
        self.verticalLayout.addWidget(self.CmdEnter)
        self.gridLayout.addWidget(self.Terminal_Group, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1021, 21))
        self.menubar.setObjectName("menubar")
        self.menuMapping = QtWidgets.QMenu(self.menubar)
        self.menuMapping.setObjectName("menuMapping")
        self.menuMode = QtWidgets.QMenu(self.menubar)
        self.menuMode.setObjectName("menuMode")
        self.menuHome = QtWidgets.QMenu(self.menubar)
        self.menuHome.setObjectName("menuHome")
        self.menuHelp_About = QtWidgets.QMenu(self.menubar)
        self.menuHelp_About.setObjectName("menuHelp_About")
        self.menuLogs_Data = QtWidgets.QMenu(self.menubar)
        self.menuLogs_Data.setObjectName("menuLogs_Data")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLIDAR = QtWidgets.QAction(MainWindow)
        self.actionLIDAR.setObjectName("actionLIDAR")
        self.actionKinect_Depth_Cam = QtWidgets.QAction(MainWindow)
        self.actionKinect_Depth_Cam.setObjectName("actionKinect_Depth_Cam")
        self.actionManuel = QtWidgets.QAction(MainWindow)
        self.actionManuel.setObjectName("actionManuel")
        self.actionAutomatic = QtWidgets.QAction(MainWindow)
        self.actionAutomatic.setObjectName("actionAutomatic")
        self.actionUser_Manual = QtWidgets.QAction(MainWindow)
        self.actionUser_Manual.setObjectName("actionUser_Manual")
        self.actionContact_Developer = QtWidgets.QAction(MainWindow)
        self.actionContact_Developer.setObjectName("actionContact_Developer")
        self.actionVersion_Info = QtWidgets.QAction(MainWindow)
        self.actionVersion_Info.setObjectName("actionVersion_Info")
        self.actionCheck_for_Updates = QtWidgets.QAction(MainWindow)
        self.actionCheck_for_Updates.setObjectName("actionCheck_for_Updates")
        self.actionView_Logs = QtWidgets.QAction(MainWindow)
        self.actionView_Logs.setObjectName("actionView_Logs")
        self.actionExport_Logs = QtWidgets.QAction(MainWindow)
        self.actionExport_Logs.setObjectName("actionExport_Logs")
        self.actionSensor_History = QtWidgets.QAction(MainWindow)
        self.actionSensor_History.setObjectName("actionSensor_History")
        self.actionSystem_Status = QtWidgets.QAction(MainWindow)
        self.actionSystem_Status.setObjectName("actionSystem_Status")
        self.actionConnection_Settings = QtWidgets.QAction(MainWindow)
        self.actionConnection_Settings.setObjectName("actionConnection_Settings")
        self.actionRobot_Parameters = QtWidgets.QAction(MainWindow)
        self.actionRobot_Parameters.setObjectName("actionRobot_Parameters")
        self.actionLanguage = QtWidgets.QAction(MainWindow)
        self.actionLanguage.setObjectName("actionLanguage")
        self.actionAppearance_Dark_Light_Mode = QtWidgets.QAction(MainWindow)
        self.actionAppearance_Dark_Light_Mode.setObjectName("actionAppearance_Dark_Light_Mode")
        self.actionView_Map = QtWidgets.QAction(MainWindow)
        self.actionView_Map.setObjectName("actionView_Map")
        self.actionExport_Map = QtWidgets.QAction(MainWindow)
        self.actionExport_Map.setObjectName("actionExport_Map")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuMapping.addAction(self.actionLIDAR)
        self.menuMapping.addAction(self.actionKinect_Depth_Cam)
        self.menuMapping.addAction(self.actionView_Map)
        self.menuMapping.addAction(self.actionExport_Map)
        self.menuMode.addAction(self.actionManuel)
        self.menuMode.addAction(self.actionAutomatic)
        self.menuHome.addAction(self.actionOpen)
        self.menuHelp_About.addAction(self.actionUser_Manual)
        self.menuHelp_About.addAction(self.actionContact_Developer)
        self.menuHelp_About.addAction(self.actionVersion_Info)
        self.menuHelp_About.addAction(self.actionCheck_for_Updates)
        self.menuLogs_Data.addAction(self.actionView_Logs)
        self.menuLogs_Data.addAction(self.actionExport_Logs)
        self.menuLogs_Data.addAction(self.actionSensor_History)
        self.menuLogs_Data.addAction(self.actionSystem_Status)
        self.menuSettings.addAction(self.actionConnection_Settings)
        self.menuSettings.addAction(self.actionRobot_Parameters)
        self.menubar.addAction(self.menuMapping.menuAction())
        self.menubar.addAction(self.menuMode.menuAction())
        self.menubar.addAction(self.menuHome.menuAction())
        self.menubar.addAction(self.menuHelp_About.menuAction())
        self.menubar.addAction(self.menuLogs_Data.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.Speed_horizontalSlideR.valueChanged['int'].connect(self.Speed_Value.setNum) # type: ignore
        self.Speed_horizontalSlideR.valueChanged['int'].connect(self.Speed_Value2.setNum) # type: ignore
        self.Freen_Slider.valueChanged['int'].connect(self.Fren_Value.setNum) # type: ignore
        self.Turn_Speed_Slider.valueChanged['int'].connect(self.Turn_Speed_value.setNum) # type: ignore
        self.Capa_Slider.valueChanged['int'].connect(self.Capa_Value.setNum) # type: ignore
        self.Freen_Slider.valueChanged['int'].connect(self.Speed_Value_4.setNum) # type: ignore
        self.Turn_Speed_Slider.valueChanged['int'].connect(self.Speed_Value_2.setNum) # type: ignore
        self.Capa_Slider.valueChanged['int'].connect(self.Speed_Value_3.setNum) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Main_Title.setText(_translate("MainWindow", "AGRIEDGE CONTROL PANNEL"))
        self.groupBox.setTitle(_translate("MainWindow", "Informations"))
        self.Mod_label.setText(_translate("MainWindow", "Mod:"))
        self.Mod_Value.setText(_translate("MainWindow", "Default"))
        self.system_label.setText(_translate("MainWindow", "System Status"))
        self.system_value.setText(_translate("MainWindow", "Kapalı"))
        self.Battery_Label.setText(_translate("MainWindow", "Battery:"))
        self.Battery_Value.setText(_translate("MainWindow", "0"))
        self.haritalama_label.setText(_translate("MainWindow", "Mapping Status"))
        self.haritalama_value.setText(_translate("MainWindow", "Baslamadı"))
        self.Temp_Label.setText(_translate("MainWindow", "Temperature"))
        self.Temp_Value.setText(_translate("MainWindow", "0"))
        self.capalama_label.setText(_translate("MainWindow", "Hoeing Status"))
        self.capalama_value.setText(_translate("MainWindow", "Baslamadı"))
        self.Location_Label.setText(_translate("MainWindow", "Location"))
        self.Loc_X_Val.setText(_translate("MainWindow", "x: 0"))
        self.Loc_Y_Val.setText(_translate("MainWindow", "y: 0"))
        self.loglama_label.setText(_translate("MainWindow", "Logging"))
        self.loglama_value.setText(_translate("MainWindow", "Baslamadı"))
        self.Speed_Label.setText(_translate("MainWindow", "Speed"))
        self.Speed_Value.setText(_translate("MainWindow", "0"))
        self.Speed_Label_2.setText(_translate("MainWindow", "Turning Speed"))
        self.Speed_Value_2.setText(_translate("MainWindow", "0"))
        self.Speed_Label_4.setText(_translate("MainWindow", "Brake"))
        self.Speed_Value_4.setText(_translate("MainWindow", "0"))
        self.Speed_Label_3.setText(_translate("MainWindow", "Hoeing Depth"))
        self.Speed_Value_3.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "Warning:"))
        self.Detail_Check_Box.setText(_translate("MainWindow", "Detailed Information Mode"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Control Butons"))
        self.ConnectButon.setText(_translate("MainWindow", "Connect"))
        self.DisconnectButton.setText(_translate("MainWindow", "Disconnect"))
        self.StartMapping.setText(_translate("MainWindow", "Start Mapping"))
        self.StopMapping.setText(_translate("MainWindow", "Stop Maping"))
        self.CapalamaStart.setText(_translate("MainWindow", "Hoeing Start"))
        self.CapalamaStop.setText(_translate("MainWindow", "Hoeing Stop"))
        self.log_start_buton.setText(_translate("MainWindow", "Log Start"))
        self.log_stop_buton.setText(_translate("MainWindow", "Log Stop"))
        self.Speed_Bar.setText(_translate("MainWindow", "Speed"))
        self.Speed_Value2.setText(_translate("MainWindow", "0  "))
        self.Turn_Speed_Bar.setText(_translate("MainWindow", "Turning Speed"))
        self.Turn_Speed_value.setText(_translate("MainWindow", "0"))
        self.Fren_Bar.setText(_translate("MainWindow", "Brake"))
        self.Fren_Value.setText(_translate("MainWindow", "0"))
        self.Capa_Bar.setText(_translate("MainWindow", "Hoeing Depth"))
        self.Capa_Value.setText(_translate("MainWindow", "0"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Robot Cam View"))
        self.Terminal_Group.setTitle(_translate("MainWindow", "Control Window"))
        self.menuMapping.setTitle(_translate("MainWindow", "Mapping"))
        self.menuMode.setTitle(_translate("MainWindow", "Mode"))
        self.menuHome.setTitle(_translate("MainWindow", "Home"))
        self.menuHelp_About.setTitle(_translate("MainWindow", "Help / About"))
        self.menuLogs_Data.setTitle(_translate("MainWindow", "Logs / Data"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionLIDAR.setText(_translate("MainWindow", "LIDAR"))
        self.actionLIDAR.setShortcut(_translate("MainWindow", "Shift+L"))
        self.actionKinect_Depth_Cam.setText(_translate("MainWindow", "Kinect Depth Cam"))
        self.actionKinect_Depth_Cam.setShortcut(_translate("MainWindow", "Shift+K"))
        self.actionManuel.setText(_translate("MainWindow", "Manuel"))
        self.actionManuel.setShortcut(_translate("MainWindow", "Shift+M"))
        self.actionAutomatic.setText(_translate("MainWindow", "Auto"))
        self.actionAutomatic.setShortcut(_translate("MainWindow", "Shift+A"))
        self.actionUser_Manual.setText(_translate("MainWindow", "User Manual"))
        self.actionUser_Manual.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.actionContact_Developer.setText(_translate("MainWindow", "Contact Developer"))
        self.actionContact_Developer.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.actionVersion_Info.setText(_translate("MainWindow", "Version Info"))
        self.actionVersion_Info.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actionCheck_for_Updates.setText(_translate("MainWindow", "Check for Updates"))
        self.actionCheck_for_Updates.setShortcut(_translate("MainWindow", "Ctrl+U"))
        self.actionView_Logs.setText(_translate("MainWindow", "View Logs"))
        self.actionView_Logs.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionExport_Logs.setText(_translate("MainWindow", "Export Logs"))
        self.actionExport_Logs.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionSensor_History.setText(_translate("MainWindow", "Sensor History"))
        self.actionSensor_History.setShortcut(_translate("MainWindow", "Ctrl+H"))
        self.actionSystem_Status.setText(_translate("MainWindow", "System Status"))
        self.actionSystem_Status.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionConnection_Settings.setText(_translate("MainWindow", "Connection Settings"))
        self.actionConnection_Settings.setShortcut(_translate("MainWindow", "Shift+C"))
        self.actionRobot_Parameters.setText(_translate("MainWindow", "Robot Parameters"))
        self.actionRobot_Parameters.setShortcut(_translate("MainWindow", "Shift+R"))
        self.actionLanguage.setText(_translate("MainWindow", "Language"))
        self.actionAppearance_Dark_Light_Mode.setText(_translate("MainWindow", "Appearance (Dark/Light Mode)"))
        self.actionAppearance_Dark_Light_Mode.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionView_Map.setText(_translate("MainWindow", "View Map"))
        self.actionExport_Map.setText(_translate("MainWindow", "Export Map"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Shift+O"))
